import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import clsx from "clsx";

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx("text-primary", poppins.className)}>
        {children}
      </body>
    </html>
  );
}
